//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int id { get; set; }
        public System.DateTime checkDate { get; set; }
        public int userId { get; set; }
        public decimal totalCheck { get; set; }
        public string status { get; set; }
    }
}
