//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecksItem
    {
        public int id { get; set; }
        public int CheckId { get; set; }
        public int ItemId { get; set; }
        public decimal QTY { get; set; }
        public decimal price { get; set; }
        public decimal totalPrice { get; set; }
    }
}
