//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string DES { get; set; }
        public int CategoryId { get; set; }
        public decimal price { get; set; }
        public byte[] itemImg { get; set; }
        public string notes { get; set; }
        public string Name { get; set; }
    }
}
