//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceipt
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public decimal QTY { get; set; }
        public decimal totalPrice { get; set; }
    }
}
